// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEVDC495bwdEGcr1YuwbGVwtiHkcZcBlI',
    appId: '1:821886866560:web:95cbfc275dda151a2dc265',
    messagingSenderId: '821886866560',
    projectId: 'villageapp-564fe',
    authDomain: 'villageapp-564fe.firebaseapp.com',
    storageBucket: 'villageapp-564fe.firebasestorage.app',
    measurementId: 'G-X0KHCRCX6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7V_LO4gcqFeBU5jS1jdhGL6oXOmaJbUw',
    appId: '1:821886866560:android:a4786b9a7b685ed12dc265',
    messagingSenderId: '821886866560',
    projectId: 'villageapp-564fe',
    storageBucket: 'villageapp-564fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV80muPSGQyle6m4Xh82QDg8ZQ07f8ZWM',
    appId: '1:821886866560:ios:f68b737c67217fb72dc265',
    messagingSenderId: '821886866560',
    projectId: 'villageapp-564fe',
    storageBucket: 'villageapp-564fe.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV80muPSGQyle6m4Xh82QDg8ZQ07f8ZWM',
    appId: '1:821886866560:ios:f68b737c67217fb72dc265',
    messagingSenderId: '821886866560',
    projectId: 'villageapp-564fe',
    storageBucket: 'villageapp-564fe.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEVDC495bwdEGcr1YuwbGVwtiHkcZcBlI',
    appId: '1:821886866560:web:f7201136c44e2a1a2dc265',
    messagingSenderId: '821886866560',
    projectId: 'villageapp-564fe',
    authDomain: 'villageapp-564fe.firebaseapp.com',
    storageBucket: 'villageapp-564fe.firebasestorage.app',
    measurementId: 'G-LS59VVV090',
  );
}
