// localization_constants.dart

class LocalizationConstants {
  static const Map<String, Map<String, String>> localizedTexts = {
    'en': {
      'auth_required': 'Authentication Required',
      'setup_biometrics':
          'Set up Face ID or Fingerprint in your device settings for quick and secure access.',
      'try_again': 'Try Again',
      'current_account': 'CURRENT ACCOUNT',
      'current_network': 'CURRENT NETWORK',
      'total_balance': 'Total Balance',
      'home': 'Home',
      'history': 'History',
      'send': 'Send',
      'settings': 'Settings',
      'transaction_history': 'Transaction History',
      'received': 'Received',
      'fee': 'Fee',
      'previous': 'Previous',
      'next': 'Next',
      'recipient_address': 'Recipient Address',
      'amount': 'Amount',
      'estimated_tran_fee': 'Estimated Transaction Fee',
      'confirm': 'Confirm',
      'transaction': 'Transaction',
      'to': 'To',
      'from': 'From',
      'network_fee': 'Network Fee',
      'cancel': 'Cancel',
      'alert_send':
          'Transaction cannot be reversed once confirmed. Please verify all details carefully.',
      'my_accounts': 'My Accounts',
      'done': 'Done',
      'hide_private_key': 'Hide Private Key',
      'create_account': 'Create Account',
      'import_account': 'Import Account',
      'my_wallets': 'MY WALLETS',
      'imported': 'Imported',
      'account_details': 'Account Details',
      'balance': 'Balance',
      'created_wallet': 'Created Wallet',
      'imported_wallet': 'Imported Wallet',
      'wallet_address_qr': 'Wallet Address QR Code',
      'wallet_address': 'Wallet Address',
      'full_address': 'Full Address',
      'public_address': 'Public Address',
      'private_key': 'Private Key',
      'caution': 'CAUTION: Never share your private key with anyone!',
      'reveal_private_key': 'Reveal Private Key',
      'transaction_details': 'Transaction Details',
      'hash': 'Hash',
      'date': 'Date',
      'close': 'Close',
      'network': 'Network',
      'appearance': 'Appearance',
      'language': 'Language',
      'choose_language': 'Choose Language',
      'mainnet_networks': 'MAINNET NETWORKS',
      'test_networks': 'TEST NETWORKS',
      'not_implemented': 'Not Implemented',
      'crypto_vault': 'Crypto Vault',
      'select_network': 'Select Network',
      'no_history': 'No History',
      'sent': 'Sent',
      'status': 'Status',
      'words': 'Words',
      'mnemonic': 'Mnemonic',
      'new_wallet': 'New Wallet',
      'create': 'Create',
      'create_new_account': 'Create New Account',
      'import': 'Import',
      'enter_your_private_key': 'Enter your private key',
      'import_error': 'Import Error',
      'ok': 'Ok',
      'import_wallet': 'Import Wallet',
      'dark_mode': 'Dark Mode',
      'selected_language': 'Selected Language',
      'transaction_sent': 'Transaction Sent Successfully',
      'success': 'Success',
      'select_token': 'Select Token',
    },
    'ta': {
      'auth_required': 'அங்கீகாரம் தேவை',
      'setup_biometrics':
          'விரைவான மற்றும் பாதுகாப்பான அணுகலுக்காக, உங்கள் சாதன அமைப்புகளில் முக அடையாளம் அல்லது விரல் ரேகை அமைப்பை அமைக்கவும்.',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'current_account': 'தற்போதைய கணக்கு',
      'current_network': 'தற்போதைய இணைப்பிணைப்பு',
      'total_balance': 'மொத்த இருப்பு',
      'home': 'வீடு',
      'history': 'வரலாறு',
      'send': 'அனுப்பு',
      'no_history': 'வரலாறு இல்லை',
      'settings': 'அமைப்புகள்',
      'transaction_history': 'பரிவர்த்தனை வரலாறு',
      'received': 'பெறப்பட்டது',
      'fee': 'கட்டணம்',
      'sent': 'அனுப்பப்பட்டது',
      'previous': 'முந்தைய',
      'next': 'அடுத்தது',
      'recipient_address': 'பெறுநர் முகவரி',
      'amount': 'தொகை',
      'estimated_tran_fee': 'மதிப்பிடப்பட்ட பரிவர்த்தனை கட்டணம்',
      'confirm': 'உறுதி',
      'transaction': 'பரிவர்த்தனை',
      'to': 'க்கு',
      'from': 'இருந்து',
      'network_fee': 'இணையத்தள கட்டணம்',
      'cancel': 'ரத்து',
      'alert_send':
          'பரிவர்த்தனை உறுதிப்படுத்தப்பட்டவுடன் திரும்பப் பெற முடியாது. தயவுசெய்து அனைத்து விவரங்களையும் கவனமாக சரிபார்க்கவும்.',
      'my_accounts': 'எனது கணக்குகள்',
      'done': 'முடிந்தது',
      'create_account': 'கணக்கு உருவாக்கு',
      'select_network': 'இணையத்தளத்தைத் தேர்ந்தெடுக்கவும்',
      'import_account': 'கணக்கு இறக்குமதி',
      'my_wallets': 'எனது பணப்பைகள்',
      'imported': 'இறக்குமதி செய்யப்பட்டது',
      'account_details': 'கணக்கு விவரங்கள்',
      'balance': 'இருப்பு',
      'created_wallet': 'உருவாக்கப்பட்ட பணப்பை',
      'imported_wallet': 'இறக்குமதி செய்யப்பட்ட பணப்பை',
      'wallet_address_qr': 'பணப்பை முகவரி QR குறியீடு',
      'wallet_address': 'பணப்பை முகவரி',
      'full_address': 'முழு முகவரி',
      'public_address': 'பொது முகவரி',
      'private_key': 'தனியார் விசை',
      'caution':
          'எச்சரிக்கை: உங்கள் தனியார் விசையை யாருடனும் பகிர்ந்து கொள்ள வேண்டாம்!',
      'reveal_private_key': 'தனியார் விசையை வெளிப்படுத்தவும்',
      'hide_private_key': 'தனியார் விசையை மறை',
      'transaction_details': 'பரிவர்த்தனை விவரங்கள்',
      'hash': 'ஹாஷ்',
      'date': 'தேதி',
      'close': 'மூடு',
      'network': 'இணையத்தளம்',
      'appearance': 'தோற்றம்',
      'status': 'நிலை',
      'language': 'மொழி',
      'import': 'இறக்குமதி',
      'choose_language': 'மொழி தேர்ந்தெடுக்கவும்',
      'mainnet_networks': 'முதன்மை இணையத்தளங்கள்',
      'test_networks': 'சோதனை இணையத்தளங்கள்',
      'not_implemented': 'செயல்படுத்தப்படவில்லை',
      'crypto_vault': 'கிரிப்டோ வால்ட்',
      'words': 'வார்த்தைகள்',
      'mnemonic': 'ஞாபகவார்த்தை',
      'create': 'உருவாக்கு',
      'new_wallet': 'புதிய பணப்பை',
      'create_new_account': 'புதிய கணக்கு உருவாக்கு',
      'import_error': 'இறக்குமதி பிழை',
      'ok': 'சரி',
      'enter_your_private_key': 'உங்கள் தனியார் விசையை உள்ளிடவும்',
      'import_wallet': 'பணப்பை இறக்குமதி',
      'dark_mode': 'இருண்ட முறை',
      'selected_language': 'தேர்ந்தெடுக்கப்பட்ட மொழி',
      'transaction_sent': 'பரிவர்த்தனை வெற்றிகரமாக அனுப்பப்பட்டது',
      'success': 'வெற்றி',
      'select_token': 'டோக்கனைத் தேர்ந்தெடுக்கவும்',
    }
  };
}
